[object]
id = "65e5a49f49147e1c1d27d46b"
name = "SAYMON (10.0.2.15)"
class_id = 3
child_ids = [
    "65e5a4a149147e1c1d27d471",
    "65e5a4a649147e1c1d27d478",
    "65e5a4a649147e1c1d27d47f",
    "65e5a4a749147e1c1d27d486",
    "65e5a4a949147e1c1d27d48d",
]
child_link_ids = []
child_ref_ids = []
owner_id = ""
parent_id = [
    1,
]
discovery_id = "10.0.2.15"
properties = [
    { name = "IP", type_id = 1, value = "10.0.2.15", id = "65e5a49e49147e1c1d27d469" },
    { name = "Hostname", type_id = 1, value = "SAYMON", id = "65e5a49e49147e1c1d27d46a" },
]
client_data = ""
state_id = 4
tags = []
background = ""
created = 1709548702952
geoposition = []
geopositionRadius = ""
last_state_update = 1710229175326
manual_state = ""
operations = "[]"
updated = 1709548702945
weight = 1

[state-conditions]
conditions = " "

[stat-rules]
rules = " "

[state-triggers]
triggers = " "
